### PR TITLE
graph init: Disambiguate names, spread tuples over multiple entity fields

### LINKED ISSUE #253: Conversion from 'AssemblyScript' to 'Value' for source type 'EthereumTuple' is not supported
When trying load in an ABI local file for a deployed contract, I get the following error:

```
Error: Conversion from 'AssemblyScript' to 'Value' for source type 'EthereumTuple' is not supported
    at findConversionFromType (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/codegen/types/index.js:42:11)
    at valueTypeForAsc (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/codegen/types/index.js:96:3)
    at ethereumTypeToGraphQL (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/scaffold.js:89:10)
    at event.inputs.map (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/scaffold.js:97:50)
    at Array.map (<anonymous>)
    at generateEventType (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/scaffold.js:95:10)
    at Array.map (<anonymous>)
    at generateSchema (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/scaffold.js:107:8)
    at generateScaffold (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/scaffold.js:152:16)
    at withSpinner (/Users/brockelmore/.nvm/versions/node/v8.12.0/lib/node_modules/@graphprotocol/graph-cli/src/commands/init.js:529:28)
```

### PR DESCRIPTION
**Pull request by Jannis**
Resolves #253.

Apart from adding a reusable name disambiguation helper for events, functions, event inputs and function inputs and outputs, this adds the following:

1. Entity type names, event names and event handlers generated by `graph init` are now disambiguated using the same logic as is used by `graph codegen`.

2. Event parameters that are of type `tuple` are now translated to multiple fields on the generated event entity type.

### CODE REVIEW

File: src/scaffold.js [hunk 1]
```diff
@@ -60,11 +76,11 @@ dataSources:
       abi: Contract
     mapping:
       kind: ethereum/events
-      apiVersion: 0.0.1
+      apiVersion: 0.0.2
```
Comment (leodasvacas) [inline src/scaffold.js]: Since we're doing this big PR to fix `graph init` issue before the release, should we also update the `'@graphprotocol/graph-ts'` version in this file?

**Comment by leodasvacas** [comment]
Since we're doing this big PR to fix `graph init` issues before the release, should we also update the `'@graphprotocol/graph-ts'` version that's used in scaffolding? I think that would be the fix for #257.

**Review by leoyvens — APPROVED** [review]
Awesome, tests look great. My comment is about something we should also do as part of the release, but it's probably best to merge this and do it as a follow up.
