### PR TITLE
CLI: Handle unknown commands, improve error handling

### LINKED ISSUE #121: `graph unknown-command subgraph.yaml` fails with a 'Failed to load subgraph' error
When you run
```
graph generate-types subgraph.yaml
```
or
```
graph foo subgraph.yaml
```

it fails with a `Failed to load subgraph` error, which is very confusing and incorrect. It should instead tell users that `generate-types`/`foo` is an unknown command and then probably print the usage/help text.

### LINKED ISSUE #129: Improve non-verbose output
Without `--verbosity verbose` or `--verbosity debug`, we're printing a bunch of empty lines here and there. It generally looks untidy and sometimes (`codegen`) there isn't any feedback at all.

### PR DESCRIPTION
**Pull request by Jannis**
Resolves #121. Resolves #129.

This PR moves all CLI commands into a single script, makes all command line flags global and provides useful errors about unknown commands and missing flags:

# Missing `subgraph.yaml`

```
$ graph build

  error: missing required argument `subgraph-manifest'
```

# No command supplied

```
$ graph
Usage: graph [options] [command]

Options:

  -V, --version                     output the version number
  --verbosity <info|verbose|debug>  The log level to use (default: LOG_LEVEL or info) (default: info)
  --debug                           Alias for --verbosity debug
  --verbose                         Alias for --verbosity verbose
  -o, --output-dir <path>           Output directory for build artifacts (default: /Users/jannis/Work/graphprotocol/subgraphs/adchain-subgraph/dist)
  -w, --watch                       Rebuild automatically when files change
  -g, --node <URL>[:PORT]           Graph node
  -t, --output-format <wasm|wast>   Output format (wasm, wast) (default: wasm)
  -i, --ipfs <addr>                 IPFS node to use for uploading files
  -n, --subgraph-name <NAME>        Subgraph name
  --api-key <KEY>                   Graph API key corresponding to the subgraph name
  -h, --help                        output usage information

Commands:

  codegen <subgraph-manifest>       Generates TypeScript types for a subgraph
  build <subgraph-manifest>         Compiles a subgraph and uploads it to IPFS
  deploy <subgraph-manifest>        Deploys the subgraph to a graph node
```

# Missing flag

```
$ graph deploy subgraph.yaml

Configuration:

  Subgraph name: No name defined with -n/--subgraph-name
  Graph node:    No node defined with -g/--node
  IPFS:          No node defined with -i/--ipfs

--
For more information run this command with --help
```

# Unknown command

```
$ graph foo
Unknown command: foo
--
Usage: graph [options] [command]

Options:

  -V, --version                     output the version number
  --verbosity <info|verbose|debug>  The log level to use (default: LOG_LEVEL or info) (default: info)
  -o, --output-dir <path>           Output directory for build artifacts (default: /Users/jannis/Work/graphprotocol/subgraphs/mind-subgraph/dist)
  -w, --watch                       Rebuild automatically when files change
  -g, --node <URL>[:PORT]           Graph node
  -t, --output-format <wasm|wast>   Output format (wasm, wast) (default: wasm)
  -i, --ipfs <addr>                 IPFS node to use for uploading files
  -n, --subgraph-name <NAME>        Subgraph name
  --api-key <KEY>                   Graph API key corresponding to the subgraph name
  -h, --help                        output usage information

Commands:

  codegen <subgraph-manifest>       Generates TypeScript types for a subgraph
  build <subgraph-manifest>         Compiles a subgraph and uploads it to IPFS
  deploy <subgraph-manifest>        Deploys the subgraph to a graph node

Configuration:

  Subgraph name: No name defined with -n/--subgraph-name
  Graph node:    No node defined with -g/--node
  IPFS:          No node defined with -i/--ipfs
```

# Verbosity levels

## Default (`info`)

```
$ graph build subgraph.yaml
Types generated
Build completed
Subgraph: /Users/jannis/Work/graphprotocol/subgraphs/adchain-subgraph/dist/subgraph.yaml
```

## Verbose (`--verbosity verbose` or `--verbose`)

```
$ graph build subgraph.yaml --verbose
1/11 Load subgraph: subgraph.yaml

2/11 Create build directory

3/11 Copy subgraph to build directory

4/11 Generate types from contract ABIs

  1/3 Load subgraph

  2/3 Load contract ABIs

  3/3 Generate types for contract ABIs

  Types generated

5/11 Copy runtime to build directory

6/11 Add generated types to runtime

7/11 Add mappings to runtime

8/11 Create output directory: dist

9/11 Compile subgraph

10/11 Write compiled subgraph to output directory

Build completed

Subgraph: /Users/jannis/Work/graphprotocol/subgraphs/adchain-subgraph/dist/subgraph.yaml
```

## Debug (`--verbosity debug` or `--debug`)

```
$ graph build subgraph.yaml --debug
1/11 Load subgraph: subgraph.yaml

2/11 Create build directory

3/11 Copy subgraph to build directory
Copy subgraph file: <build>/schema.graphql
Write subgraph file: <build>/AdNetworks/abis/adNetworks.json
Copy subgraph file: <build>/AdNetworks/mappings/ad-networks.ts

4/11 Generate types from contract ABIs

  1/3 Load subgraph

  2/3 Load contract ABIs

  3/3 Generate types for contract ABIs
  Generate types for contract ABI: Registry (adNetworks.json)
  Write types to: <build>/AdNetworks/Registry.types.ts

  Types generated

5/11 Copy runtime to build directory
Copy runtime file: <build>/AdNetworks/index.ts

6/11 Add generated types to runtime
Add types from file to runtime: <build>/AdNetworks/Registry.types.ts

7/11 Add mappings to runtime

8/11 Create output directory: dist

9/11 Compile subgraph
Compile data source mapping: AdNetworks => <build>/AdNetworks/AdNetworks.wasm

10/11 Write compiled subgraph to output directory
Copy subgraph file: dist/schema.graphql
Copy subgraph file: dist/AdNetworks/abis/adNetworks.json
Copy subgraph file: dist/AdNetworks/AdNetworks.wasm
Write runtime source: dist/AdNetworks/AdNetworks.ts
Write subgraph manifest: dist/subgraph.yaml

Build completed

Subgraph: /Users/jannis/Work/graphprotocol/subgraphs/adchain-subgraph/dist/subgraph.yaml
```

# Errors

## Default verbosity (`info`)

```
$ graph build subgraph.yaml
Failed to compile subgraph Failed to copy subgraph files: Error: ENOENT: no such file or directory, open './abis/adNetworks.jsonfoo'
```

## Verbose (`--verbosity verbose` or `--verbose`)

```
$ graph build subgraph.yaml --verbose
1/11 Load subgraph: subgraph.yaml

2/11 Create build directory

3/11 Copy subgraph to build directory
Failed to compile subgraph Failed to copy subgraph files: Error: ENOENT: no such file or directory, open './abis/adNetworks.jsonfoo'
```

## Debug (`--verbosity debug` or `--debug`)

```
$ graph build subgraph.yaml --debug
1/11 Load subgraph: subgraph.yaml

2/11 Create build directory

3/11 Copy subgraph to build directory
Copy subgraph file: <build>/schema.graphql
Failed to compile subgraph Failed to copy subgraph files: Error: ENOENT: no such file or directory, open './abis/adNetworks.jsonfoo'
    at Compiler.copySubgraph (/Users/jannis/Work/graphprotocol/graph-cli/src/cli/compiler.js:190:13)
    at Compiler.compile (/Users/jannis/Work/graphprotocol/graph-cli/src/cli/compiler.js:46:37)
    at Command.app.command.description.action.subgraphManifest (/Users/jannis/Work/graphprotocol/graph-cli/graph.js:114:16)
    at Command.listener (/Users/jannis/Work/graphprotocol/graph-cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/Users/jannis/Work/graphprotocol/graph-cli/node_modules/commander/index.js:654:12)
    at Command.parse (/Users/jannis/Work/graphprotocol/graph-cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/jannis/Work/graphprotocol/graph-cli/graph.js:198:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

### CODE REVIEW

**Comment by Jannis** [comment]
In this PR, `graph` by itself, without any arguments, doesn't print a help text. That should be fixed.

File: graph.js [hunk 1]
```diff
@@ -1,12 +1,194 @@
...
+    console.log('  Graph node:    No node defined with -g/--node')
+  } else {
+    console.log(`  Graph node:    ${app.node}`)
+  }
+
+  if (app.ipfs === undefined) {
+    console.log('  IPFS:          No node defined with -i/--ipfs')
+  } else {
+    console.log(`  IPFS:          ${app.ipfs}`)
+  }
```
Comment (leodasvacas) [inline graph.js]: Is this mostly a placeholder for when we have an external way to configure these parameters? It's strange for `--help` to take parameters.

File: graph.js [hunk 2]
```diff
@@ -1,12 +1,194 @@
...
+      console.error('Error: No Graph node specified with -g/--node')
+      console.error('--')
+      app.help()
+    }
+
+    if (app.ipfs == undefined) {
+      console.error('Error: No IPFS node specified with -i/--ipfs')
+      console.error('--')
+      app.help()
+    }
```
Comment (leodasvacas) [inline graph.js]: Can we change this so that it report errors for all missing parameters?

Do we really want to print the whole help when there is an error in an argument? The actual error gets lost in the help text. I'd rather print "For more information try --help".

**Review by leoyvens — CHANGES_REQUESTED** [review]
Left some comments. Something I noticed got worse with this PR, if you type only `graph deploy` on master, you get the help text. If you do the same on this branch you get only "error: missing required argument `subgraph-manifest'" which is unhelpful.

File: graph.js (hunk 1 above)
Comment (Jannis) [reply graph.js]: I see your point, this could be confusing. I'll change this to only log when there's missing configuration.

File: graph.js (hunk 2 above)
Comment (Jannis) [reply graph.js]: Yep, I'll update.

**Comment by Jannis** [comment]
@leodasvacas Updated things a little:

* Improve error messages by not swallowing internal errors.
* Add `--verbose` and `--debug` CLI flags.
* Clean up newlines in different verbosity levels.
* Only dump the config when something is missing. Don't show a help text then.
* Show help text when `graph` is executed without supplying a command.

Let me know what you think.

**Comment by Jannis** [comment]
@leodasvacas About the `missing required argument 'subgraph-manifest'` error: previously, the subgraph manifest argument was marked as optional, which did not make sense. I agree the help message could be more helpful but the argument should be required like it is now.

**Comment by leodasvacas** [comment]
@Jannis I like how you addressed the inline comments!

To illustrate my observation, this is `graph deploy` on master:
image

This is it on this branch:
image

Sure the manifest is mandatory and that's a good fix, but the current message is much more informative. Would it be difficult to keep this similar to what it currently is?

**Comment by Jannis** [comment]
@leodasvacas Well, the first message doesn't tell you that anything is missing, because `[subgraph.yaml]` means that argument is optional. That's not great either.

I'll see what I can do.

**Comment by leodasvacas** [comment]
Printing the same as `graph deploy --help` would be an improvement:
image

But that has also gotten worse in comparison to master in the aspect that it no longer prints all options.

**Comment by Jannis** [comment]
There's only so much we can do with `commander`, unfortunately.

**Comment by Jannis** [comment]
@leodasvacas I have an idea: How about we make the manifest argument optional (defaulting to `subgraph.yaml`)? I'll push an update to this branch in a few minutes.

**Comment by Jannis** [comment]
Alright, I've made a bunch of changes:

## `subgraph.yaml` is now optional

As a consequence, you can run `graph codegen`, `graph build` and `graph deploy` with supplying a `subgraph.yaml` file. It'll default to `$PWD/subgraph.yaml`.

## Options have been moved back into the different subcommands

This way you can run e.g. `graph deploy --help` again and it'll show you all the options you have for that command specifically. The only options that are now global are `--debug`, `--verbose` and `--verbosity <LEVEL>`.

## The output is less verbose

Only `--debug` now prints empty lines a la

image

Both `--verbose` and `--verbosity info` (default) are more compact:

image

## Errors while setting up the watcher or collecting files to watch are now handled

Previously, an error during the watcher setup would look like this:

image

Errors collecting files (e.g. due to a broken manifest) while already watching would silently cause the watcher to terminate.

We now catch errors on setup:

image

and while already watching (allowing to recover from these):

image

**Comment by Jannis** [comment]
## Unknown commands are caught as before

image

**Review by leoyvens — APPROVED** [review]
Great polish, just one observation about having blank lines only on debug. Considering that causes some code duplication, could we just ditch the newlines all together?

**Comment by Jannis** [comment]
@leodasvacas The logging code isn't pretty but for the moment I'd like to preserve the newlines.
