### PR TITLE
fix: remove validate studio network checks

### LINKED ISSUE #1509: Remove validateStudioNetwork during deploy
We are removing network limitations on the studio, so this check is no longer required.

### PR DESCRIPTION
**Pull request by saihaj**
Studio will take care of this and we don't need to maintain a list for supported networks.

closes #1509

### CODE REVIEW

File: packages/cli/src/commands/init.ts [hunk 1]
```diff
@@ -245,8 +244,6 @@ export default class InitCommand extends Command {
           subgraphName,
           contractName,
           node,
-          studio,
```
Comment (azf20) [inline packages/cli/src/commands/init.ts:248]: Is this already removing some arguments from `init`?

**Review by azf20 — CHANGES_REQUESTED** [review]
Nice! Does this already remove `studio` args from `init`? (Just checking if that was intended)

File: packages/cli/src/commands/init.ts (hunk 1 above)
Comment (saihaj) [reply packages/cli/src/commands/init.ts:248]: no we are not removing any args. This is simply removing the validation check since we only do that check during `init` fro `studio`. Should not change any args.

**Review by azf20 — APPROVED** [review]

**Review by dotansimha — APPROVED** [review]
