### PR TITLE
fix graph test command regressions

### LINKED ISSUE #1191: `graph test` command regressions
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

It seems there are some regressions in the `graph test` command since `v0.40.0`:

1. The `datasource` argument is made `required`, while it should be optional https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/commands/test.ts#L16
2. `--version`, `-v` options is also marked as required, but it should be optional https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/commands/test.ts#L51
3. It seems the `cachePath` will always point to the default location in the `./tests` folder https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/commands/test.ts#L61-L62, which affects also the version cache https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/commands/test.ts#L72. Specifying another test folder location through the `matchstick.yaml` file will do nothing, because the lookup happens at a later stage here https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/commands/test.ts#L75 and it will always create and save the cache file in the default `./tests` folder instead in the one specified by the config.

### Reproduction

https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/commands/test.ts#L16

### Steps to Reproduce the Bug or Issue

1. Run `graph test` without any arguments using graph-cli `0.42.4`

### Expected behavior

1. `graph test` should run without any arguments
2. First the lookup for a custom test folder from `matchstick.yaml` should happen before setting the `testDir` and `cachePath` and the the lookup for the cached matchstick version

### Screenshots or Videos
1. and 2.
Screenshot 2023-03-16 at 22 42 15

3.
Screenshot 2023-03-16 at 22 52 00

### Platform

- `@graphprotocol/graph-cli` "0.42.4"

### Subgraph Manifest

_No response_

### Subgraph GraphQL Schema

_No response_

### Additional context

### PR DESCRIPTION
**Pull request by saihaj**
Making `datasource` and `version` optional args to `graph test`

- [x] Need to find a way to repro and fix `cachePath` for `graph test`

Fixes #1191

### CODE REVIEW

File: packages/cli/src/commands/test.ts [hunk 1]
```diff
@@ -58,30 +55,17 @@ export default class TestCommand extends Command {
...
         // Load the config
         const config = await yaml.load(filesystem.read('matchstick.yaml', 'utf8')!);
-
-        // Check if matchstick.yaml and testsDir not null
-        if (config?.testsDir) {
+        // Check if matchstick.yaml and testsFolder not null
+        if (config?.testsFolder) {
           // assign test folder from matchstick.yaml if present
-          opts.testsDir = config.testsDir;
+          testsDir = config.testsFolder;
```
Comment (saihaj) [inline packages/cli/src/commands/test.ts:68]: we were not using the correct value here so it was just wrong

**Review by dimitrovmaksim — APPROVED** [review]
LGTM. Tested with the demo-subgraph in both binary and docker mode

**Review by enisdenjo — APPROVED** [review]
